---
- name: Upload verification script
  copy:
    src: "files/ceph-version-qemu.sh"
    dest: "/root/ceph-version-qemu.sh"
    owner: root
    group: root
    mode: 500
  tags: script
  no_log: true
- name: Run verification script
  shell: /root/ceph-version-qemu.sh "{{ '-e' if exclude_rbd=='true' else '' }}" "{{ '-d' if script_debug=='true' else '' }}"
  changed_when: False
